apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-pod
spec:
  containers:
  - name: ephemeral-pod
    image: alpine
    command: ["/bin/sh", "-c", "while true; do echo 'Running...'; sleep 5; done"]
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "0.1"
        memory: "256Mi"
  terminationGracePeriodSeconds: 20
